In [6]:
#coding=utf-8
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [10]:
cal = A.sum(axis=0)
#axis=0 竖直相加
#axis=1 水平相加
print(cal)
print(cal.reshape(1,4))

[  59.   239.   155.4   76.9]
[[  59.   239.   155.4   76.9]]


In [11]:
percentage = 100*A/cal.reshape(1,4)
#A(3,4)   cal(1,4)  reshape是o(1)效率

In [12]:
print percentage

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]
